### ISSUE TITLE
Minor: find articles button 

### ISSUE THREAD

**Issue by pranita122** [Purple-Recovery/purple-recovery#12]
I'm not really sure what the purpose of "find articles" on the main page under Responses is supposed to do. Initially, I thought it would lead to some sort of search engine to find more such articles, but it just led to a page with the exact same links as on the home page. You might want to discuss the purpose of that page/make the wording of the button more clear.

**Comment by kylerws** [comment]
Hi there! The dashboard was intended to show the three most recently added articles on the site. The purpose of the "find articles" page is to display more articles beyond those three.

In our design, we decided against implementing any search engine type feature, and against automatically pulling articles from the UW website. This was because the problem with the current UW website was an overload of unorganized information. Instead, the Purple Recovery team will select the most important articles offered by UW and manually add those to the site. 

We agree that the name "Find Articles" suggests some kind of search functionality, so we have changed the button text to read "More Articles" instead.
